"""customerFollowingVendor

Revision ID: afc9073408d5
Revises: 54d386b49243
Create Date: 2023-01-10 22:26:18.882478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc9073408d5'
down_revision = '54d386b49243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
