"""customerFollowingVendor

Revision ID: 9ee98a402f4b
Revises: afc9073408d5
Create Date: 2023-01-10 22:31:18.829711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee98a402f4b'
down_revision = 'afc9073408d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
