"""added schedule table

Revision ID: 9265cbfd6881
Revises: 54a68e25a358
Create Date: 2023-01-10 22:01:57.324791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9265cbfd6881'
down_revision = '54a68e25a358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
