"""added schedule table

Revision ID: 54d386b49243
Revises: a14384181dd9
Create Date: 2023-01-10 22:18:35.202460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d386b49243'
down_revision = 'a14384181dd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
