"""YOUR MIGRATION TITLE

Revision ID: 54a68e25a358
Revises: a032ac500a81
Create Date: 2023-01-10 21:47:05.214417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a68e25a358'
down_revision = 'a032ac500a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
