# Generated by Django 4.1.3 on 2022-11-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0002_schedule_user_vendorfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorfollowing',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
