# Generated by Django 4.1.3 on 2022-11-07 04:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0003_rename_vendor_id_vendorfollowing_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='businessCategoryID',
        ),
        migrations.RemoveField(
            model_name='vendorfollowing',
            name='vendor',
        ),
        migrations.AddField(
            model_name='schedule',
            name='userId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='nomad.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='businessType',
            field=models.CharField(choices=[(1, 'Food and Beverages'), (2, 'Clothes')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='emptyForNow', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, default=0, related_name='user_followers', to='nomad.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, default=0, related_name='user_follows', to='nomad.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='geolocation',
            field=models.CharField(default='emptyForNow', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='global_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_name',
            field=models.CharField(default='emptyForNow', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='emptyForNow', upload_to='ProfilePicture/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Customer', 'Customer')], default='Vendor', max_length=10),
        ),
        migrations.DeleteModel(
            name='BusinessCategory',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorFollowing',
        ),
    ]
