# Generated by Django 4.1.3 on 2022-11-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0005_rename_userid_schedule_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessTypeName', models.CharField(default='emptyForNow', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='businessType',
        ),
        migrations.AddField(
            model_name='user',
            name='businessTypeID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='nomad.businesstype'),
        ),
    ]
